// Generated by gencpp from file serial_node/rawpose.msg
// DO NOT EDIT!


#ifndef SERIAL_NODE_MESSAGE_RAWPOSE_H
#define SERIAL_NODE_MESSAGE_RAWPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial_node
{
template <class ContainerAllocator>
struct rawpose_
{
  typedef rawpose_<ContainerAllocator> Type;

  rawpose_()
    : qw(0.0)
    , qx(0.0)
    , qy(0.0)
    , qz(0.0)  {
    }
  rawpose_(const ContainerAllocator& _alloc)
    : qw(0.0)
    , qx(0.0)
    , qy(0.0)
    , qz(0.0)  {
  (void)_alloc;
    }



   typedef float _qw_type;
  _qw_type qw;

   typedef float _qx_type;
  _qx_type qx;

   typedef float _qy_type;
  _qy_type qy;

   typedef float _qz_type;
  _qz_type qz;





  typedef boost::shared_ptr< ::serial_node::rawpose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_node::rawpose_<ContainerAllocator> const> ConstPtr;

}; // struct rawpose_

typedef ::serial_node::rawpose_<std::allocator<void> > rawpose;

typedef boost::shared_ptr< ::serial_node::rawpose > rawposePtr;
typedef boost::shared_ptr< ::serial_node::rawpose const> rawposeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_node::rawpose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_node::rawpose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::serial_node::rawpose_<ContainerAllocator1> & lhs, const ::serial_node::rawpose_<ContainerAllocator2> & rhs)
{
  return lhs.qw == rhs.qw &&
    lhs.qx == rhs.qx &&
    lhs.qy == rhs.qy &&
    lhs.qz == rhs.qz;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::serial_node::rawpose_<ContainerAllocator1> & lhs, const ::serial_node::rawpose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace serial_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::serial_node::rawpose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_node::rawpose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_node::rawpose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_node::rawpose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_node::rawpose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_node::rawpose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_node::rawpose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d378075a646e7fc335d7346a31fdc29";
  }

  static const char* value(const ::serial_node::rawpose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d378075a646e7fcULL;
  static const uint64_t static_value2 = 0x335d7346a31fdc29ULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_node::rawpose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_node/rawpose";
  }

  static const char* value(const ::serial_node::rawpose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_node::rawpose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 qw\n"
"float32 qx\n"
"float32 qy\n"
"float32 qz\n"
;
  }

  static const char* value(const ::serial_node::rawpose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_node::rawpose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.qw);
      stream.next(m.qx);
      stream.next(m.qy);
      stream.next(m.qz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rawpose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_node::rawpose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_node::rawpose_<ContainerAllocator>& v)
  {
    s << indent << "qw: ";
    Printer<float>::stream(s, indent + "  ", v.qw);
    s << indent << "qx: ";
    Printer<float>::stream(s, indent + "  ", v.qx);
    s << indent << "qy: ";
    Printer<float>::stream(s, indent + "  ", v.qy);
    s << indent << "qz: ";
    Printer<float>::stream(s, indent + "  ", v.qz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_NODE_MESSAGE_RAWPOSE_H
